export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID || "awmgkhticthegwazfkoq";
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3bWdraHRpY3RoZWd3YXpma29xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3NTc5NDYsImV4cCI6MjA3ODMzMzk0Nn0.T7INttoyLNgyz9AoLL_6thrc9A2H_ykSbMuroDPOzAk";
