export const categories = [
  {
    slug: "sofas",
    name: "Sofas & Couches",
    description: "Comfortable and stylish sofas for your living space",
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80",
  },
  {
    slug: "chairs",
    name: "Chairs",
    description: "Elegant chairs for every room",
    image: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&q=80",
  },
  {
    slug: "tables",
    name: "Tables",
    description: "Dining, coffee, and side tables",
    image: "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=800&q=80",
  },
  {
    slug: "beds",
    name: "Beds & Bedroom",
    description: "Luxurious beds for perfect sleep",
    image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80",
  },
  {
    slug: "storage",
    name: "Storage",
    description: "Stylish storage solutions",
    image: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=800&q=80",
  },
];

// Image pools for variety
const sofaImages = [
  "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&q=80",
  "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=1200&q=80",
  "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=1200&q=80",
  "https://images.unsplash.com/photo-1550254478-ead40cc54513?w=1200&q=80",
  "https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=1200&q=80",
  "https://images.unsplash.com/photo-1538688273852-e29027c0c176?w=1200&q=80",
  "https://images.unsplash.com/photo-1550226891-ef816aed4a98?w=1200&q=80",
  "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&q=80",
  "https://images.unsplash.com/photo-1567016432779-094069958ea5?w=1200&q=80",
];

const chairImages = [
  "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=1200&q=80",
  "https://images.unsplash.com/photo-1503602642458-232111445657?w=1200&q=80",
  "https://images.unsplash.com/photo-1581539250439-c96689b516dd?w=1200&q=80",
  "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=1200&q=80",
  "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=1200&q=80",
  "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=1200&q=80",
];

const tableImages = [
  "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=1200&q=80",
  "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=1200&q=80",
  "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=1200&q=80",
  "https://images.unsplash.com/photo-1551298370-9d3d53740c72?w=1200&q=80",
  "https://images.unsplash.com/photo-1611269154421-4e27233ac5c7?w=1200&q=80",
  "https://images.unsplash.com/photo-1565191999001-551c187427bb?w=1200&q=80",
];

const bedImages = [
  "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=80",
  "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=1200&q=80",
  "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=1200&q=80",
  "https://images.unsplash.com/photo-1583221742001-9ad88bf233ff?w=1200&q=80",
];

const storageImages = [
  "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=1200&q=80",
  "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=1200&q=80",
  "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&q=80",
];

// Helper function to generate products
function generateProduct(config: any) {
  return {
    id: config.id,
    name: config.name,
    slug: config.slug,
    category: config.category,
    price: config.price,
    originalPrice: config.originalPrice,
    currency: "AUD",
    description: config.description,
    features: config.features,
    images: config.images,
    dimensions: config.dimensions,
    sizes: config.sizes,
    customizable: config.customizable,
    colors: config.colors,
    materials: config.materials,
    inStock: true,
    featured: config.featured || false,
    rating: config.rating || 4.5 + Math.random() * 0.4,
    reviews: config.reviews || Math.floor(Math.random() * 200) + 50,
  };
}

export const products = [
  // ========== SOFAS (30 products) ==========
  generateProduct({
    id: "sofa-cloud-modern",
    name: "Cloud Modern Sofa",
    slug: "cloud-modern-sofa",
    category: "sofas",
    price: 2499,
    originalPrice: 3299,
    description: "Experience ultimate comfort with our Cloud Modern Sofa. Featuring deep seating, plush cushions, and a timeless design.",
    features: ["Premium fabric upholstery", "Solid hardwood frame", "High-density foam cushions", "Removable covers", "10-year warranty"],
    images: [sofaImages[0], sofaImages[1], sofaImages[2]],
    dimensions: { width: 220, depth: 95, height: 85, unit: "cm" },
    sizes: ["2-Seater", "3-Seater"],
    customizable: true,
    colors: [
      { name: "Beige", hex: "#E8E4D9", image: sofaImages[0] },
      { name: "Charcoal", hex: "#2C3E50", image: sofaImages[1] },
      { name: "Grey", hex: "#7F8C8D", image: sofaImages[2] },
    ],
    materials: [
      { name: "Linen", image: sofaImages[0] },
      { name: "Velvet", image: sofaImages[8] },
      { name: "Performance Fabric", image: sofaImages[1] },
    ],
    featured: true,
    rating: 4.8,
    reviews: 234,
  }),
  
  generateProduct({
    id: "sofa-sectional-l",
    name: "L-Shaped Sectional Sofa",
    slug: "l-shaped-sectional-sofa",
    category: "sofas",
    price: 3499,
    originalPrice: 4299,
    description: "Spacious L-shaped sectional perfect for large living rooms. Modular design allows for flexible configuration.",
    features: ["Modular sectional design", "Reversible chaise", "Deep seating comfort", "Stain-resistant fabric", "15-year warranty"],
    images: [sofaImages[3], sofaImages[4], sofaImages[5]],
    dimensions: { width: 280, depth: 220, height: 90, unit: "cm" },
    sizes: ["L-Shape"],
    customizable: true,
    colors: [
      { name: "Light Grey", hex: "#D3D3D3", image: sofaImages[3] },
      { name: "Dark Grey", hex: "#696969", image: sofaImages[4] },
      { name: "Navy", hex: "#2F4F4F", image: sofaImages[5] },
    ],
    materials: [
      { name: "Performance Fabric", image: sofaImages[3] },
      { name: "Linen", image: sofaImages[4] },
      { name: "Leather", image: sofaImages[8] },
    ],
    featured: true,
    rating: 4.9,
    reviews: 312,
  }),

  generateProduct({
    id: "sofa-chesterfield",
    name: "Classic Chesterfield Sofa",
    slug: "classic-chesterfield-sofa",
    category: "sofas",
    price: 2899,
    originalPrice: 3699,
    description: "Timeless Chesterfield design with button-tufted upholstery and rolled arms.",
    features: ["Hand-tufted buttons", "Rolled arms design", "Genuine leather option", "Solid wood legs", "Classic British style"],
    images: [sofaImages[6], sofaImages[7], sofaImages[0]],
    dimensions: { width: 200, depth: 90, height: 78, unit: "cm" },
    sizes: ["2-Seater", "3-Seater"],
    customizable: true,
    colors: [
      { name: "Brown Leather", hex: "#8B4513", image: sofaImages[6] },
      { name: "Black Leather", hex: "#1C1C1C", image: sofaImages[7] },
      { name: "Tan Leather", hex: "#D2B48C", image: sofaImages[0] },
    ],
    materials: [
      { name: "Genuine Leather", image: sofaImages[6] },
      { name: "Faux Leather", image: sofaImages[7] },
    ],
    featured: false,
    rating: 4.7,
    reviews: 189,
  }),

  generateProduct({
    id: "sofa-mid-century",
    name: "Mid-Century Modern Sofa",
    slug: "mid-century-modern-sofa",
    category: "sofas",
    price: 2199,
    originalPrice: 2899,
    description: "Retro-inspired mid-century design with tapered wooden legs and clean lines.",
    features: ["Tapered wooden legs", "Button-tufted back", "Compact design", "Perfect for small spaces", "Vintage aesthetics"],
    images: [sofaImages[2], sofaImages[0], sofaImages[1]],
    dimensions: { width: 180, depth: 85, height: 80, unit: "cm" },
    sizes: ["2-Seater", "3-Seater"],
    customizable: true,
    colors: [
      { name: "Mustard", hex: "#FFDB58", image: sofaImages[2] },
      { name: "Teal", hex: "#008080", image: sofaImages[0] },
      { name: "Orange", hex: "#FF8C00", image: sofaImages[1] },
    ],
    materials: [
      { name: "Fabric", image: sofaImages[2] },
      { name: "Velvet", image: sofaImages[8] },
    ],
    featured: true,
    rating: 4.6,
    reviews: 156,
  }),

  generateProduct({
    id: "sofa-sleeper",
    name: "Convertible Sleeper Sofa",
    slug: "convertible-sleeper-sofa",
    category: "sofas",
    price: 1999,
    originalPrice: 2599,
    description: "Multi-functional sofa that converts into a comfortable bed for guests.",
    features: ["Easy conversion mechanism", "Memory foam mattress", "Storage compartment", "Ideal for apartments", "Modern design"],
    images: [sofaImages[0], sofaImages[1], sofaImages[2]],
    dimensions: { width: 200, depth: 90, height: 85, unit: "cm" },
    sizes: ["3-Seater"],
    customizable: false,
    colors: [
      { name: "Grey", hex: "#808080", image: sofaImages[0] },
      { name: "Navy", hex: "#000080", image: sofaImages[1] },
    ],
    materials: [
      { name: "Performance Fabric", image: sofaImages[0] },
    ],
    featured: false,
    rating: 4.5,
    reviews: 98,
  }),

  // Additional 25 sofas with variations...
  ...Array.from({ length: 25 }, (_, i) => generateProduct({
    id: `sofa-${i + 6}`,
    name: `${['Luxe', 'Modern', 'Classic', 'Elegant', 'Comfort', 'Premium', 'Deluxe', 'Contemporary', 'Vintage', 'Scandinavian'][i % 10]} ${['Lounge', 'Loveseat', 'Sofa', 'Settee', 'Couch', 'Sectional'][i % 6]}`,
    slug: `sofa-${i + 6}`,
    category: "sofas",
    price: 1699 + (i * 150),
    originalPrice: 2199 + (i * 200),
    description: `Premium quality sofa designed for modern living spaces. Features comfortable seating and durable construction.`,
    features: ["Premium materials", "Comfortable design", "Durable construction", "Easy maintenance"],
    images: [sofaImages[i % sofaImages.length], sofaImages[(i + 1) % sofaImages.length], sofaImages[(i + 2) % sofaImages.length]],
    dimensions: { width: 180 + (i * 10), depth: 85, height: 80, unit: "cm" },
    sizes: [["2-Seater", "3-Seater", "L-Shape"][i % 3]],
    customizable: i % 2 === 0,
    colors: [
      { name: "Color 1", hex: ["#E8E4D9", "#2C3E50", "#7F8C8D", "#808080", "#D3D3D3"][i % 5], image: sofaImages[i % sofaImages.length] },
      { name: "Color 2", hex: ["#696969", "#2F4F4F", "#8B4513", "#000080", "#36454F"][i % 5], image: sofaImages[(i + 1) % sofaImages.length] },
    ],
    materials: [
      { name: ["Linen", "Velvet", "Fabric", "Leather", "Performance Fabric"][i % 5], image: sofaImages[i % sofaImages.length] },
    ],
    featured: i % 5 === 0,
  })),

  // ========== CHAIRS (25 products) ==========
  generateProduct({
    id: "dining-chair-nordic",
    name: "Nordic Dining Chair",
    slug: "nordic-dining-chair",
    category: "chairs",
    price: 349,
    originalPrice: 499,
    description: "Scandinavian-inspired dining chair with a sleek profile and exceptional comfort.",
    features: ["Solid oak wood legs", "Ergonomic backrest design", "Padded seat cushion", "Easy assembly", "Available in sets"],
    images: [chairImages[0], chairImages[1], chairImages[2]],
    dimensions: { width: 45, depth: 52, height: 82, unit: "cm" },
    sizes: ["Dining"],
    customizable: true,
    colors: [
      { name: "White", hex: "#F5F5F5", image: chairImages[0] },
      { name: "Charcoal", hex: "#2C3E50", image: chairImages[1] },
      { name: "Walnut", hex: "#8B4513", image: chairImages[2] },
    ],
    materials: [
      { name: "Oak Wood", image: chairImages[0] },
      { name: "Walnut Wood", image: chairImages[2] },
      { name: "Ash Wood", image: chairImages[1] },
    ],
    featured: true,
    rating: 4.7,
    reviews: 156,
  }),

  generateProduct({
    id: "accent-chair-velvet",
    name: "Velvet Accent Chair",
    slug: "velvet-accent-chair",
    category: "chairs",
    price: 599,
    originalPrice: 799,
    description: "Luxurious velvet accent chair with a modern silhouette.",
    features: ["Soft velvet upholstery", "Comfortable padded seat", "Sturdy wooden legs", "Modern curved design", "Perfect for small spaces"],
    images: [chairImages[3], chairImages[4], chairImages[5]],
    dimensions: { width: 70, depth: 75, height: 80, unit: "cm" },
    sizes: ["Armchair"],
    customizable: true,
    colors: [
      { name: "Forest Green", hex: "#2C5F2D", image: chairImages[3] },
      { name: "Navy", hex: "#1C2833", image: chairImages[4] },
      { name: "Purple", hex: "#6C3483", image: chairImages[5] },
    ],
    materials: [
      { name: "Velvet", image: chairImages[3] },
    ],
    featured: false,
    rating: 4.7,
    reviews: 134,
  }),

  ...Array.from({ length: 23 }, (_, i) => generateProduct({
    id: `chair-${i + 3}`,
    name: `${['Executive', 'Dining', 'Lounge', 'Office', 'Accent', 'Wingback', 'Rocking', 'Ergonomic'][i % 8]} Chair ${i + 3}`,
    slug: `chair-${i + 3}`,
    category: "chairs",
    price: 299 + (i * 50),
    originalPrice: 399 + (i * 70),
    description: `Comfortable and stylish chair perfect for any room in your home.`,
    features: ["Comfortable design", "Durable construction", "Easy assembly", "Modern style"],
    images: [chairImages[i % chairImages.length], chairImages[(i + 1) % chairImages.length]],
    dimensions: { width: 50, depth: 55, height: 85, unit: "cm" },
    sizes: [["Dining", "Armchair", "Lounge", "Standard"][i % 4]],
    customizable: i % 2 === 0,
    colors: [
      { name: "Color 1", hex: ["#F5F5F5", "#2C3E50", "#8B4513", "#808080"][i % 4], image: chairImages[i % chairImages.length] },
      { name: "Color 2", hex: "#696969", image: chairImages[(i + 1) % chairImages.length] },
    ],
    materials: [
      { name: ["Oak Wood", "Velvet", "Fabric", "Leather"][i % 4], image: chairImages[i % chairImages.length] },
    ],
    featured: i % 6 === 0,
  })),

  // ========== TABLES (25 products) ==========
  generateProduct({
    id: "table-oak-dining",
    name: "Oak Dining Table",
    slug: "oak-dining-table",
    category: "tables",
    price: 1899,
    originalPrice: 2499,
    description: "A stunning solid oak dining table that seats up to 8 people.",
    features: ["100% solid oak construction", "Natural wood grain patterns", "Seats 6-8 people", "Protective finish coating", "Expandable option"],
    images: [tableImages[0], tableImages[1], tableImages[2]],
    dimensions: { width: 200, depth: 100, height: 75, unit: "cm" },
    sizes: ["6-Seater", "8-Seater"],
    customizable: true,
    colors: [
      { name: "Natural Oak", hex: "#8B4513", image: tableImages[0] },
      { name: "Dark Oak", hex: "#D2691E", image: tableImages[1] },
      { name: "Light Oak", hex: "#5C4033", image: tableImages[2] },
    ],
    materials: [
      { name: "Oak", image: tableImages[0] },
      { name: "Walnut", image: tableImages[1] },
      { name: "Ash", image: tableImages[2] },
    ],
    featured: true,
    rating: 4.9,
    reviews: 189,
  }),

  generateProduct({
    id: "coffee-table-marble",
    name: "Marble Coffee Table",
    slug: "marble-coffee-table",
    category: "tables",
    price: 899,
    originalPrice: 1199,
    description: "Sophisticated marble top coffee table with gold metal legs.",
    features: ["Genuine marble top", "Brushed gold metal frame", "Heat and stain resistant", "Easy to clean surface", "Anti-scratch protectors"],
    images: [tableImages[3], tableImages[4], tableImages[5]],
    dimensions: { width: 120, depth: 60, height: 45, unit: "cm" },
    sizes: ["Round", "Square"],
    customizable: false,
    colors: [
      { name: "White Marble", hex: "#FFFFFF", image: tableImages[3] },
      { name: "Black Marble", hex: "#000000", image: tableImages[4] },
    ],
    materials: [
      { name: "Marble", image: tableImages[3] },
      { name: "Gold Metal", image: tableImages[4] },
    ],
    featured: false,
    rating: 4.5,
    reviews: 72,
  }),

  ...Array.from({ length: 23 }, (_, i) => generateProduct({
    id: `table-${i + 3}`,
    name: `${['Dining', 'Coffee', 'Console', 'Side', 'Desk', 'End'][i % 6]} Table ${i + 3}`,
    slug: `table-${i + 3}`,
    category: "tables",
    price: 599 + (i * 100),
    originalPrice: 799 + (i * 130),
    description: `Beautiful table crafted with quality materials and modern design.`,
    features: ["Quality construction", "Modern design", "Easy assembly", "Durable finish"],
    images: [tableImages[i % tableImages.length], tableImages[(i + 1) % tableImages.length]],
    dimensions: { width: 120 + (i * 10), depth: 70, height: 75, unit: "cm" },
    sizes: [["4-Seater", "6-Seater", "8-Seater", "Round", "Square"][i % 5]],
    customizable: i % 2 === 0,
    colors: [
      { name: "Wood Tone", hex: ["#8B4513", "#D2691E", "#5C4033", "#A0522D"][i % 4], image: tableImages[i % tableImages.length] },
    ],
    materials: [
      { name: ["Oak", "Walnut", "Marble", "Glass", "Metal"][i % 5], image: tableImages[i % tableImages.length] },
    ],
    featured: i % 7 === 0,
  })),

  // ========== BEDS (15 products) ==========
  generateProduct({
    id: "bed-luxe-upholstered",
    name: "Luxe Upholstered Bed",
    slug: "luxe-upholstered-bed",
    category: "beds",
    price: 2199,
    originalPrice: 2899,
    description: "Elegant upholstered bed frame with a luxurious headboard.",
    features: ["Premium upholstered headboard", "Solid pine slat support", "No box spring required", "Available in Queen & King", "Easy assembly"],
    images: [bedImages[0], bedImages[1], bedImages[2]],
    dimensions: { width: 165, depth: 215, height: 120, unit: "cm" },
    sizes: ["Queen", "King"],
    customizable: true,
    colors: [
      { name: "Beige", hex: "#F5F5DC", image: bedImages[0] },
      { name: "Grey", hex: "#708090", image: bedImages[1] },
      { name: "Navy", hex: "#2F4F4F", image: bedImages[2] },
    ],
    materials: [
      { name: "Linen", image: bedImages[0] },
      { name: "Velvet", image: bedImages[1] },
      { name: "Bouclé", image: bedImages[2] },
    ],
    featured: true,
    rating: 4.6,
    reviews: 98,
  }),

  ...Array.from({ length: 14 }, (_, i) => generateProduct({
    id: `bed-${i + 2}`,
    name: `${['Platform', 'Storage', 'Panel', 'Sleigh', 'Canopy', 'Upholstered'][i % 6]} Bed ${i + 2}`,
    slug: `bed-${i + 2}`,
    category: "beds",
    price: 1699 + (i * 150),
    originalPrice: 2199 + (i * 200),
    description: `Quality bed frame designed for comfort and style.`,
    features: ["Solid construction", "Modern design", "Easy assembly", "Durable materials"],
    images: [bedImages[i % bedImages.length], bedImages[(i + 1) % bedImages.length]],
    dimensions: { width: 150 + (i * 5), depth: 200, height: 110, unit: "cm" },
    sizes: [["Single", "Double", "Queen", "King"][i % 4]],
    customizable: i % 2 === 0,
    colors: [
      { name: "Color", hex: ["#F5F5DC", "#708090", "#2F4F4F", "#E6E6FA"][i % 4], image: bedImages[i % bedImages.length] },
    ],
    materials: [
      { name: ["Linen", "Velvet", "Fabric", "Wood"][i % 4], image: bedImages[i % bedImages.length] },
    ],
    featured: i % 5 === 0,
  })),

  // ========== STORAGE (15 products) ==========
  generateProduct({
    id: "sideboard-modern",
    name: "Modern Sideboard",
    slug: "modern-sideboard",
    category: "storage",
    price: 1299,
    originalPrice: 1699,
    description: "Sleek modern sideboard with ample storage space.",
    features: ["Soft-close drawers", "Adjustable internal shelving", "Cable management cutouts", "Scratch-resistant surface", "Wall-mounting option"],
    images: [storageImages[0], storageImages[1], storageImages[2]],
    dimensions: { width: 180, depth: 45, height: 80, unit: "cm" },
    sizes: ["Large"],
    customizable: true,
    colors: [
      { name: "White", hex: "#FFFFFF", image: storageImages[0] },
      { name: "Charcoal", hex: "#2C3E50", image: storageImages[1] },
      { name: "Oak", hex: "#8B7355", image: storageImages[2] },
    ],
    materials: [
      { name: "Oak", image: storageImages[2] },
      { name: "Walnut", image: storageImages[1] },
      { name: "White Lacquer", image: storageImages[0] },
    ],
    featured: false,
    rating: 4.6,
    reviews: 87,
  }),

  ...Array.from({ length: 14 }, (_, i) => generateProduct({
    id: `storage-${i + 2}`,
    name: `${['Bookcase', 'Cabinet', 'Dresser', 'Chest', 'Wardrobe', 'Shelf Unit'][i % 6]} ${i + 2}`,
    slug: `storage-${i + 2}`,
    category: "storage",
    price: 699 + (i * 100),
    originalPrice: 899 + (i * 130),
    description: `Practical storage solution with modern design and quality construction.`,
    features: ["Ample storage space", "Quality materials", "Modern design", "Easy assembly"],
    images: [storageImages[i % storageImages.length], storageImages[(i + 1) % storageImages.length]],
    dimensions: { width: 100 + (i * 20), depth: 45, height: 80 + (i * 10), unit: "cm" },
    sizes: [["Small", "Medium", "Large", "XL"][i % 4]],
    customizable: i % 2 === 0,
    colors: [
      { name: "Finish", hex: ["#FFFFFF", "#2C3E50", "#8B7355", "#A0522D"][i % 4], image: storageImages[i % storageImages.length] },
    ],
    materials: [
      { name: ["Oak", "Walnut", "Pine", "White Lacquer"][i % 4], image: storageImages[i % storageImages.length] },
    ],
    featured: i % 6 === 0,
  })),
];

// Sample orders
const orders = [
  {
    id: '550e8400-e29b-41d4-a716-446655440001',
    userId: 'customer-001',
    customerEmail: 'sarah.johnson@example.com',
    customerName: 'Sarah Johnson',
    items: [
      {
        productId: 'sofa-001',
        name: 'Cloud Modern Sofa',
        price: 2499,
        quantity: 1,
        image: sofaImages[0],
      },
      {
        productId: 'chair-001',
        name: 'Nordic Dining Chair',
        price: 349,
        quantity: 4,
        image: chairImages[0],
      },
    ],
    total: 3895,
    status: 'completed',
    paymentMethod: 'card',
    shippingAddress: {
      street: '123 Main Street',
      city: 'Adelaide',
      state: 'SA',
      postcode: '5000',
      country: 'Australia',
    },
    createdAt: new Date('2024-11-10T10:30:00').toISOString(),
    updatedAt: new Date('2024-11-12T14:20:00').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440002',
    userId: 'customer-002',
    customerEmail: 'michael.chen@example.com',
    customerName: 'Michael Chen',
    items: [
      {
        productId: 'table-001',
        name: 'Scandinavian Oak Dining Table',
        price: 1899,
        quantity: 1,
        image: tableImages[0],
      },
      {
        productId: 'chair-002',
        name: 'Velvet Accent Chair',
        price: 549,
        quantity: 2,
        image: chairImages[1],
      },
    ],
    total: 2997,
    status: 'processing',
    paymentMethod: 'card',
    shippingAddress: {
      street: '456 King William Road',
      city: 'North Adelaide',
      state: 'SA',
      postcode: '5006',
      country: 'Australia',
    },
    createdAt: new Date('2024-11-13T14:15:00').toISOString(),
    updatedAt: new Date('2024-11-13T14:15:00').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440003',
    userId: 'customer-003',
    customerEmail: 'emma.wilson@example.com',
    customerName: 'Emma Wilson',
    items: [
      {
        productId: 'bed-001',
        name: 'Luxe Upholstered Bed',
        price: 2299,
        quantity: 1,
        image: bedImages[0],
      },
    ],
    total: 2299,
    status: 'completed',
    paymentMethod: 'card',
    shippingAddress: {
      street: '789 Prospect Road',
      city: 'Prospect',
      state: 'SA',
      postcode: '5082',
      country: 'Australia',
    },
    createdAt: new Date('2024-11-08T09:45:00').toISOString(),
    updatedAt: new Date('2024-11-09T11:30:00').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440004',
    userId: 'customer-004',
    customerEmail: 'james.brown@example.com',
    customerName: 'James Brown',
    items: [
      {
        productId: 'storage-001',
        name: 'Minimalist Bookshelf',
        price: 799,
        quantity: 2,
        image: storageImages[0],
      },
      {
        productId: 'table-002',
        name: 'Modern Coffee Table',
        price: 649,
        quantity: 1,
        image: tableImages[1],
      },
    ],
    total: 2247,
    status: 'shipped',
    paymentMethod: 'card',
    shippingAddress: {
      street: '321 Unley Road',
      city: 'Unley',
      state: 'SA',
      postcode: '5061',
      country: 'Australia',
    },
    createdAt: new Date('2024-11-11T16:20:00').toISOString(),
    updatedAt: new Date('2024-11-13T10:00:00').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440005',
    userId: 'customer-005',
    customerEmail: 'olivia.smith@example.com',
    customerName: 'Olivia Smith',
    items: [
      {
        productId: 'sofa-002',
        name: 'L-Shaped Sectional',
        price: 3499,
        quantity: 1,
        image: sofaImages[1],
      },
    ],
    total: 3499,
    status: 'completed',
    paymentMethod: 'card',
    shippingAddress: {
      street: '654 Fullarton Road',
      city: 'Fullarton',
      state: 'SA',
      postcode: '5063',
      country: 'Australia',
    },
    createdAt: new Date('2024-11-05T13:00:00').toISOString(),
    updatedAt: new Date('2024-11-07T15:45:00').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440006',
    userId: 'customer-006',
    customerEmail: 'william.taylor@example.com',
    customerName: 'William Taylor',
    items: [
      {
        productId: 'chair-003',
        name: 'Executive Office Chair',
        price: 699,
        quantity: 1,
        image: chairImages[2],
      },
      {
        productId: 'table-003',
        name: 'Standing Desk',
        price: 1299,
        quantity: 1,
        image: tableImages[2],
      },
    ],
    total: 1998,
    status: 'processing',
    paymentMethod: 'card',
    shippingAddress: {
      street: '987 Greenhill Road',
      city: 'Burnside',
      state: 'SA',
      postcode: '5066',
      country: 'Australia',
    },
    createdAt: new Date('2024-11-14T11:30:00').toISOString(),
    updatedAt: new Date('2024-11-14T11:30:00').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440007',
    userId: 'customer-007',
    customerEmail: 'sophia.anderson@example.com',
    customerName: 'Sophia Anderson',
    items: [
      {
        productId: 'bed-002',
        name: 'Coastal Bed Frame',
        price: 1799,
        quantity: 1,
        image: bedImages[1],
      },
      {
        productId: 'storage-002',
        name: 'Wardrobe Cabinet',
        price: 1499,
        quantity: 1,
        image: storageImages[1],
      },
    ],
    total: 3298,
    status: 'completed',
    paymentMethod: 'card',
    shippingAddress: {
      street: '147 Hutt Street',
      city: 'Adelaide',
      state: 'SA',
      postcode: '5000',
      country: 'Australia',
    },
    createdAt: new Date('2024-11-09T08:15:00').toISOString(),
    updatedAt: new Date('2024-11-10T16:30:00').toISOString(),
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440008',
    userId: 'customer-008',
    customerEmail: 'daniel.martinez@example.com',
    customerName: 'Daniel Martinez',
    items: [
      {
        productId: 'sofa-003',
        name: 'Chesterfield Sofa',
        price: 2899,
        quantity: 1,
        image: sofaImages[2],
      },
    ],
    total: 2899,
    status: 'shipped',
    paymentMethod: 'card',
    shippingAddress: {
      street: '258 Rundle Street',
      city: 'Adelaide',
      state: 'SA',
      postcode: '5000',
      country: 'Australia',
    },
    createdAt: new Date('2024-11-12T15:45:00').toISOString(),
    updatedAt: new Date('2024-11-14T09:20:00').toISOString(),
  },
];

export const seedData = {
  categories,
  products,
  orders,
};